name: agricola
description: "A new Flutter project."
publish_to: 'none'
version: 0.2.6

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  google_fonts: ^6.2.1
  go_router: ^14.6.0
  shared_preferences: ^2.3.3
  image_picker: ^1.0.7
  flutter_launcher_icons: ^0.14.4
  firebase_core: ^4.3.0
  intl: ^0.20.2
  firebase_auth: ^6.1.3
  google_sign_in: ^7.2.0
  cloud_firestore: ^6.1.1
  fpdart: ^1.2.0
  equatable: ^2.0.8
  dio: ^5.9.0
  firebase_storage: ^13.0.6
  flutter_image_compress: ^2.4.0
  path_provider: ^2.1.5
  path: ^1.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mocktail: ^1.0.4

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
